name: retouch_screen_shot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # state management
  signals: ^5.5.0

  # localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # Desktop
  screen_capturer: ^0.2.3
  hotkey_manager: ^0.2.3

  # image processing
  image: ^4.2.0
  path_provider: ^2.1.4
  pasteboard: ^0.2.0

  # utils
  shared_preferences: ^2.2.3
  flex_color_picker: ^3.4.1

dependency_overrides:
  screen_capturer_windows: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.5.11
  signals_lint: ^5.0.0

flutter:
  uses-material-design: true
  generate: true