name: retouch_screen_shot
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  image: ^4.2.0

  # Desktop packages
  screen_capturer: ^0.2.3
  hotkey_manager: ^0.2.3

dependency_overrides:
  screen_capturer_windows: 0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true